package su.terrafirmagreg.modules.animal.init;

import su.terrafirmagreg.framework.manager.content.api.IContentRegistrar;
import su.terrafirmagreg.modules.animal.content.entity.huntable.EntityAnimalBoar.EntityTypeAnimalBoar;
import su.terrafirmagreg.modules.animal.content.entity.huntable.EntityAnimalDeer.EntityTypeAnimalDeer;
import su.terrafirmagreg.modules.animal.content.entity.huntable.EntityAnimalGazelle.EntityTypeAnimalGazelle;
import su.terrafirmagreg.modules.animal.content.entity.huntable.EntityAnimalHare.EntityTypeAnimalHare;
import su.terrafirmagreg.modules.animal.content.entity.huntable.EntityAnimalMongoose.EntityTypeAnimalMongoose;
import su.terrafirmagreg.modules.animal.content.entity.huntable.EntityAnimalPheasant.EntityTypeAnimalPheasant;
import su.terrafirmagreg.modules.animal.content.entity.huntable.EntityAnimalRabbit.EntityTypeAnimalRabbit;
import su.terrafirmagreg.modules.animal.content.entity.huntable.EntityAnimalTurkey.EntityTypeAnimalTurkey;
import su.terrafirmagreg.modules.animal.content.entity.huntable.EntityAnimalWildebeest.EntityTypeAnimalWildebeest;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalAlpaca.EntityTypeAnimalAlpaca;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalCamel.EntityTypeAnimalCamel;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalChicken.EntityTypeAnimalChicken;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalCow.EntityTypeAnimalCow;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalDonkey.EntityTypeAnimalDonkey;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalDuck.EntityTypeAnimalDuck;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalGoat.EntityTypeAnimalGoat;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalGrouse.EntityTypeAnimalGrouse;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalHorse.EntityTypeAnimalHorse;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalLlama.EntityTypeAnimalLlama;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalMule.EntityTypeAnimalMule;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalMuskOx.EntityTypeAnimalMuskOx;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalOcelot.EntityTypeAnimalOcelot;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalParrot.EntityTypeAnimalParrot;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalPig.EntityTypeAnimalPig;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalQuail.EntityTypeAnimalQuail;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalSheep.EntityTypeAnimalSheep;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalWolf.EntityTypeAnimalWolf;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalYak.EntityTypeAnimalYak;
import su.terrafirmagreg.modules.animal.content.entity.livestock.EntityAnimalZebu.EntityTypeAnimalZebu;
import su.terrafirmagreg.modules.animal.content.entity.predator.EntityAnimalBlackBear.EntityTypeAnimalBlackBear;
import su.terrafirmagreg.modules.animal.content.entity.predator.EntityAnimalCougar.EntityTypeAnimalCougar;
import su.terrafirmagreg.modules.animal.content.entity.predator.EntityAnimalCoyote.EntityTypeAnimalCoyote;
import su.terrafirmagreg.modules.animal.content.entity.predator.EntityAnimalDireWolf.EntityTypeAnimalDireWolf;
import su.terrafirmagreg.modules.animal.content.entity.predator.EntityAnimalGrizzlyBear.EntityTypeAnimalGrizzlyBear;
import su.terrafirmagreg.modules.animal.content.entity.predator.EntityAnimalHyena.EntityTypeAnimalHyena;
import su.terrafirmagreg.modules.animal.content.entity.predator.EntityAnimalJackal.EntityTypeAnimalJackal;
import su.terrafirmagreg.modules.animal.content.entity.predator.EntityAnimalLion.EntityTypeAnimalLion;
import su.terrafirmagreg.modules.animal.content.entity.predator.EntityAnimalPanther.EntityTypeAnimalPanther;
import su.terrafirmagreg.modules.animal.content.entity.predator.EntityAnimalPolarBear.EntityTypeAnimalPolarBear;
import su.terrafirmagreg.modules.animal.content.entity.predator.EntityAnimalSaberTooth.EntityTypeAnimalSaberTooth;

import net.minecraftforge.fml.common.registry.EntityEntry;

public final class EntitiesAnimal {

  public static EntityEntry SHEEP;
  public static EntityEntry COW;
  public static EntityEntry GRIZZLY_BEAR;
  public static EntityEntry CHICKEN;
  public static EntityEntry PHEASANT;
  public static EntityEntry DEER;
  public static EntityEntry PIG;
  public static EntityEntry WOLF;
  public static EntityEntry RABBIT;
  public static EntityEntry HORSE;
  public static EntityEntry DONKEY;
  public static EntityEntry MULE;
  public static EntityEntry POLAR_BEAR;
  public static EntityEntry PARROT;
  public static EntityEntry LLAMA;
  public static EntityEntry OCELOT;
  public static EntityEntry PANTHER;
  public static EntityEntry DUCK;
  public static EntityEntry ALPACA;
  public static EntityEntry GOAT;
  public static EntityEntry SABER_TOOTH;
  public static EntityEntry CAMEL;
  public static EntityEntry LION;
  public static EntityEntry HYENA;
  public static EntityEntry DIRE_WOLF;
  public static EntityEntry HARE;
  public static EntityEntry BOAR;
  public static EntityEntry ZEBU;
  public static EntityEntry GAZELLE;
  public static EntityEntry WILDEBEEST;
  public static EntityEntry QUAIL;
  public static EntityEntry GROUSE;
  public static EntityEntry MONGOOSE;
  public static EntityEntry TURKEY;
  public static EntityEntry JACKAL;
  public static EntityEntry MUSKOX;
  public static EntityEntry YAK;
  public static EntityEntry BLACK_BEAR;
  public static EntityEntry COUGAR;
  public static EntityEntry COYOTE;

  public static void onRegister(IContentRegistrar registrar) {

    SHEEP = registrar.addEntity(new EntityTypeAnimalSheep());
    COW = registrar.addEntity(new EntityTypeAnimalCow());
    GRIZZLY_BEAR = registrar.addEntity(new EntityTypeAnimalGrizzlyBear());
    CHICKEN = registrar.addEntity(new EntityTypeAnimalChicken());
    PHEASANT = registrar.addEntity(new EntityTypeAnimalPheasant());
    DEER = registrar.addEntity(new EntityTypeAnimalDeer());
    PIG = registrar.addEntity(new EntityTypeAnimalPig());
    WOLF = registrar.addEntity(new EntityTypeAnimalWolf());
    RABBIT = registrar.addEntity(new EntityTypeAnimalRabbit());
    HORSE = registrar.addEntity(new EntityTypeAnimalHorse());
    DONKEY = registrar.addEntity(new EntityTypeAnimalDonkey());
    MULE = registrar.addEntity(new EntityTypeAnimalMule());
    POLAR_BEAR = registrar.addEntity(new EntityTypeAnimalPolarBear());
    PARROT = registrar.addEntity(new EntityTypeAnimalParrot());
    LLAMA = registrar.addEntity(new EntityTypeAnimalLlama());
    OCELOT = registrar.addEntity(new EntityTypeAnimalOcelot());
    PANTHER = registrar.addEntity(new EntityTypeAnimalPanther());
    DUCK = registrar.addEntity(new EntityTypeAnimalDuck());
    ALPACA = registrar.addEntity(new EntityTypeAnimalAlpaca());
    GOAT = registrar.addEntity(new EntityTypeAnimalGoat());
    SABER_TOOTH = registrar.addEntity(new EntityTypeAnimalSaberTooth());
    CAMEL = registrar.addEntity(new EntityTypeAnimalCamel());
    LION = registrar.addEntity(new EntityTypeAnimalLion());
    HYENA = registrar.addEntity(new EntityTypeAnimalHyena());
    DIRE_WOLF = registrar.addEntity(new EntityTypeAnimalDireWolf());
    HARE = registrar.addEntity(new EntityTypeAnimalHare());
    BOAR = registrar.addEntity(new EntityTypeAnimalBoar());
    ZEBU = registrar.addEntity(new EntityTypeAnimalZebu());
    GAZELLE = registrar.addEntity(new EntityTypeAnimalGazelle());
    WILDEBEEST = registrar.addEntity(new EntityTypeAnimalWildebeest());
    QUAIL = registrar.addEntity(new EntityTypeAnimalQuail());
    GROUSE = registrar.addEntity(new EntityTypeAnimalGrouse());
    MONGOOSE = registrar.addEntity(new EntityTypeAnimalMongoose());
    TURKEY = registrar.addEntity(new EntityTypeAnimalTurkey());
    JACKAL = registrar.addEntity(new EntityTypeAnimalJackal());
    MUSKOX = registrar.addEntity(new EntityTypeAnimalMuskOx());
    YAK = registrar.addEntity(new EntityTypeAnimalYak());
    BLACK_BEAR = registrar.addEntity(new EntityTypeAnimalBlackBear());
    COUGAR = registrar.addEntity(new EntityTypeAnimalCougar());
    COYOTE = registrar.addEntity(new EntityTypeAnimalCoyote());
  }
}
