package su.terrafirmagreg.modules.animal.init;

import su.terrafirmagreg.api.util.ModelUtils;
import su.terrafirmagreg.framework.manager.registry.api.IRegistryRegistrar;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalAbstractHorse;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalAlpaca;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalBlackBear;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalBoar;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalCamel;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalChicken;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalCougar;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalCow;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalCoyote;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalDeer;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalDireWolf;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalDuck;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalGazelle;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalGoat;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalGrizzlyBear;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalGrouse;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalHare;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalHorse;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalHyena;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalJackal;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalLion;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalLlama;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalMongoose;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalMuskOx;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalOcelot;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalPanther;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalParrot;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalPheasant;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalPig;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalPolarBear;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalQuail;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalRabbit;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalSaberTooth;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalTurkey;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalWildebeest;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalWolf;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalYak;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalZebu;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalBoar;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalDeer;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalGazelle;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalHare;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalMongoose;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalPheasant;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalRabbit;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalTurkey;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalWildebeest;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalAlpaca;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalCamel;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalChicken;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalCow;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalDonkey;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalDuck;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalGoat;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalGrouse;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalHorse;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalLlama;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalMule;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalMuskOx;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalOcelot;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalParrot;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalPig;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalQuail;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalSheep.EntityTypeAnimalSheep;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalWolf;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalYak;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalZebu;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalBlackBear;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalCougar;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalCoyote;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalDireWolf;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalGrizzlyBear;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalHyena;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalJackal;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalLion;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalPanther;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalPolarBear;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalSaberTooth;

import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

public final class EntitiesAnimal {

  public static EntityEntry SHEEP;
  public static EntityEntry COW;
  public static EntityEntry GRIZZLYBEAR;
  public static EntityEntry CHICKEN;
  public static EntityEntry PHEASANT;
  public static EntityEntry DEER;
  public static EntityEntry PIG;
  public static EntityEntry WOLF;
  public static EntityEntry RABBIT;
  public static EntityEntry HORSE;
  public static EntityEntry DONKEY;
  public static EntityEntry MULE;
  public static EntityEntry POLARBEAR;
  public static EntityEntry PARROT;
  public static EntityEntry LLAMA;
  public static EntityEntry OCELOT;
  public static EntityEntry PANTHER;
  public static EntityEntry DUCK;
  public static EntityEntry ALPACA;
  public static EntityEntry GOAT;
  public static EntityEntry SABERTOOTH;
  public static EntityEntry CAMEL;
  public static EntityEntry LION;
  public static EntityEntry HYENA;
  public static EntityEntry DIREWOLF;
  public static EntityEntry HARE;
  public static EntityEntry BOAR;
  public static EntityEntry ZEBU;
  public static EntityEntry GAZELLE;
  public static EntityEntry WILDEBEEST;
  public static EntityEntry QUAIL;
  public static EntityEntry GROUSE;
  public static EntityEntry MONGOOSE;
  public static EntityEntry TURKEY;
  public static EntityEntry JACKAL;
  public static EntityEntry MUSKOX;
  public static EntityEntry YAK;
  public static EntityEntry BLACKBEAR;
  public static EntityEntry COUGAR;
  public static EntityEntry COYOTE;

  public static void onRegister(IRegistryRegistrar registrar) {
    SHEEP = registrar.addEntity(new EntityTypeAnimalSheep());
    // SHEEP = registrar.addEntity("sheep", EntityAnimalSheep.class, 0xFFFFFF, 0xFF6347);
    COW = registrar.addEntity("cow", EntityAnimalCow.class, 0xA52A2A, 0xFFFFFF);
    GRIZZLYBEAR = registrar.addEntity("grizzlybear", EntityAnimalGrizzlyBear.class, 0xB22222, 0xDEB887);
    CHICKEN = registrar.addEntity("chicken", EntityAnimalChicken.class, 0x557755, 0xFFF91F);
    PHEASANT = registrar.addEntity("pheasant", EntityAnimalPheasant.class, 0x5577FF, 0xFFFA90);
    DEER = registrar.addEntity("deer", EntityAnimalDeer.class, 0x55FF55, 0x5FFAAF);
    PIG = registrar.addEntity("pig", EntityAnimalPig.class, 0xAA7722, 0xFFEBCD);
    WOLF = registrar.addEntity("wolf", EntityAnimalWolf.class, 0xB0ACAC, 0x796555);
    RABBIT = registrar.addEntity("rabbit", EntityAnimalRabbit.class, 0x885040, 0x462612);
    HORSE = registrar.addEntity("horse", EntityAnimalHorse.class, 0xA5886B, 0xABA400);
    DONKEY = registrar.addEntity("donkey", EntityAnimalDonkey.class, 0x493C32, 0x756659);
    MULE = registrar.addEntity("mule", EntityAnimalMule.class, 0x180200, 0x482D1A);
    POLARBEAR = registrar.addEntity("polarbear", EntityAnimalPolarBear.class, 0xF1FFF1, 0xA0A0A0);
    PARROT = registrar.addEntity("parrot", EntityAnimalParrot.class, 0x885040, 0xB0ACAC);
    LLAMA = registrar.addEntity("llama", EntityAnimalLlama.class, 0xA52A2A, 0xAA7722);
    OCELOT = registrar.addEntity("ocelot", EntityAnimalOcelot.class, 0x3527FA, 0x7F23A0);
    PANTHER = registrar.addEntity("panther", EntityAnimalPanther.class, 0x000066, 0x000000);
    DUCK = registrar.addEntity("duck", EntityAnimalDuck.class, 0xFFF91F, 0x462612);
    ALPACA = registrar.addEntity("alpaca", EntityAnimalAlpaca.class, 0x00CC66, 0x006633);
    GOAT = registrar.addEntity("goat", EntityAnimalGoat.class, 0xA0A0A0, 0x404040);
    SABERTOOTH = registrar.addEntity("sabertooth", EntityAnimalSaberTooth.class, 0xFF8000, 0xFFD700);
    CAMEL = registrar.addEntity("camel", EntityAnimalCamel.class, 0xA5886B, 0x006633);
    LION = registrar.addEntity("lion", EntityAnimalLion.class, 0xDAA520, 0xA0522D);
    HYENA = registrar.addEntity("hyena", EntityAnimalHyena.class, 0x666600, 0x331900);
    DIREWOLF = registrar.addEntity("direwolf", EntityAnimalDireWolf.class, 0x343434, 0x978f7e);
    HARE = registrar.addEntity("hare", EntityAnimalHare.class, 0x866724, 0xDADADA);
    BOAR = registrar.addEntity("boar", EntityAnimalBoar.class, 0x463c09, 0xe39ad8);
    ZEBU = registrar.addEntity("zebu", EntityAnimalZebu.class, 0x2c2507, 0xbcb38e);
    GAZELLE = registrar.addEntity("gazelle", EntityAnimalGazelle.class, 0xa9a76f, 0xc0ab55);
    WILDEBEEST = registrar.addEntity("wildebeest", EntityAnimalWildebeest.class, 0x696142, 0x9c8115);
    QUAIL = registrar.addEntity("quail", EntityAnimalQuail.class, 0x237ddc, 0xe3e36d);
    GROUSE = registrar.addEntity("grouse", EntityAnimalGrouse.class, 0xf7a100, 0x71ffd0);
    MONGOOSE = registrar.addEntity("mongoose", EntityAnimalMongoose.class, 0xf9f50f, 0x90ec7f);
    TURKEY = registrar.addEntity("turkey", EntityAnimalTurkey.class, 0xad1d1d, 0xeaa659);
    JACKAL = registrar.addEntity("jackal", EntityAnimalJackal.class, 0xb8762b, 0xffffff);
    MUSKOX = registrar.addEntity("muskox", EntityAnimalMuskOx.class, 0x620d55, 0xcdaf4f);
    YAK = registrar.addEntity("yak", EntityAnimalYak.class, 0x837669, 0x3e3d7c);
    BLACKBEAR = registrar.addEntity("blackbear", EntityAnimalBlackBear.class, 0x000000, 0xa18f6c);
    COUGAR = registrar.addEntity("cougar", EntityAnimalCougar.class, 0x817a00, 0xdcd889);
    COYOTE = registrar.addEntity("coyote", EntityAnimalCoyote.class, 0xb7bc88, 0xdac213);
  }

  @SideOnly(Side.CLIENT)
  public static void onClientRegister(IRegistryRegistrar registrar) {

    //ModelUtils.entity(EntityAnimalSheep.class, RenderAnimalSheep::new);
    ModelUtils.entity(EntityAnimalCow.class, RenderAnimalCow::new);
    ModelUtils.entity(EntityAnimalGrizzlyBear.class, RenderAnimalGrizzlyBear::new);
    ModelUtils.entity(EntityAnimalChicken.class, RenderAnimalChicken::new);
    ModelUtils.entity(EntityAnimalPheasant.class, RenderAnimalPheasant::new);
    ModelUtils.entity(EntityAnimalDeer.class, RenderAnimalDeer::new);
    ModelUtils.entity(EntityAnimalPig.class, RenderAnimalPig::new);
    ModelUtils.entity(EntityAnimalWolf.class, RenderAnimalWolf::new);
    ModelUtils.entity(EntityAnimalRabbit.class, RenderAnimalRabbit::new);
    ModelUtils.entity(EntityAnimalHorse.class, RenderAnimalHorse::new);
    ModelUtils.entity(EntityAnimalDonkey.class, RenderAnimalAbstractHorse::new);
    ModelUtils.entity(EntityAnimalMule.class, RenderAnimalAbstractHorse::new);
    ModelUtils.entity(EntityAnimalPolarBear.class, RenderAnimalPolarBear::new);
    ModelUtils.entity(EntityAnimalParrot.class, RenderAnimalParrot::new);
    ModelUtils.entity(EntityAnimalLlama.class, RenderAnimalLlama::new);
    ModelUtils.entity(EntityAnimalOcelot.class, RenderAnimalOcelot::new);
    ModelUtils.entity(EntityAnimalPanther.class, RenderAnimalPanther::new);
    ModelUtils.entity(EntityAnimalDuck.class, RenderAnimalDuck::new);
    ModelUtils.entity(EntityAnimalAlpaca.class, RenderAnimalAlpaca::new);
    ModelUtils.entity(EntityAnimalGoat.class, RenderAnimalGoat::new);
    ModelUtils.entity(EntityAnimalSaberTooth.class, RenderAnimalSaberTooth::new);
    ModelUtils.entity(EntityAnimalCamel.class, RenderAnimalCamel::new);
    ModelUtils.entity(EntityAnimalLion.class, RenderAnimalLion::new);
    ModelUtils.entity(EntityAnimalHyena.class, RenderAnimalHyena::new);
    ModelUtils.entity(EntityAnimalDireWolf.class, RenderAnimalDireWolf::new);
    ModelUtils.entity(EntityAnimalHare.class, RenderAnimalHare::new);
    ModelUtils.entity(EntityAnimalBoar.class, RenderAnimalBoar::new);
    ModelUtils.entity(EntityAnimalZebu.class, RenderAnimalZebu::new);
    ModelUtils.entity(EntityAnimalGazelle.class, RenderAnimalGazelle::new);
    ModelUtils.entity(EntityAnimalWildebeest.class, RenderAnimalWildebeest::new);
    ModelUtils.entity(EntityAnimalQuail.class, RenderAnimalQuail::new);
    ModelUtils.entity(EntityAnimalGrouse.class, RenderAnimalGrouse::new);
    ModelUtils.entity(EntityAnimalMongoose.class, RenderAnimalMongoose::new);
    ModelUtils.entity(EntityAnimalTurkey.class, RenderAnimalTurkey::new);
    ModelUtils.entity(EntityAnimalJackal.class, RenderAnimalJackal::new);
    ModelUtils.entity(EntityAnimalMuskOx.class, RenderAnimalMuskOx::new);
    ModelUtils.entity(EntityAnimalYak.class, RenderAnimalYak::new);
    ModelUtils.entity(EntityAnimalBlackBear.class, RenderAnimalBlackBear::new);
    ModelUtils.entity(EntityAnimalCougar.class, RenderAnimalCougar::new);
    ModelUtils.entity(EntityAnimalCoyote.class, RenderAnimalCoyote::new);
  }
}
