package su.terrafirmagreg.modules.device.init;

import su.terrafirmagreg.api.registry.RegistryManager;
import su.terrafirmagreg.modules.device.objects.blocks.BlockAlloyCalculator;
import su.terrafirmagreg.modules.device.objects.blocks.BlockBearTrap;
import su.terrafirmagreg.modules.device.objects.blocks.BlockBellows;
import su.terrafirmagreg.modules.device.objects.blocks.BlockBlastFurnace;
import su.terrafirmagreg.modules.device.objects.blocks.BlockBloom;
import su.terrafirmagreg.modules.device.objects.blocks.BlockBloomery;
import su.terrafirmagreg.modules.device.objects.blocks.BlockCellarDoor;
import su.terrafirmagreg.modules.device.objects.blocks.BlockCellarShelf;
import su.terrafirmagreg.modules.device.objects.blocks.BlockCellarWall;
import su.terrafirmagreg.modules.device.objects.blocks.BlockCharcoalForge;
import su.terrafirmagreg.modules.device.objects.blocks.BlockCharcoalPile;
import su.terrafirmagreg.modules.device.objects.blocks.BlockCrate;
import su.terrafirmagreg.modules.device.objects.blocks.BlockCrucible;
import su.terrafirmagreg.modules.device.objects.blocks.BlockElectricForge;
import su.terrafirmagreg.modules.device.objects.blocks.BlockFirePit;
import su.terrafirmagreg.modules.device.objects.blocks.BlockFreezeDryer;
import su.terrafirmagreg.modules.device.objects.blocks.BlockFridge;
import su.terrafirmagreg.modules.device.objects.blocks.BlockGreenhouseDoor;
import su.terrafirmagreg.modules.device.objects.blocks.BlockGreenhouseRoof;
import su.terrafirmagreg.modules.device.objects.blocks.BlockGreenhouseWall;
import su.terrafirmagreg.modules.device.objects.blocks.BlockGrindstone;
import su.terrafirmagreg.modules.device.objects.blocks.BlockIceBunker;
import su.terrafirmagreg.modules.device.objects.blocks.BlockInductionCrucible;
import su.terrafirmagreg.modules.device.objects.blocks.BlockInfectedAir;
import su.terrafirmagreg.modules.device.objects.blocks.BlockLatexExtractor;
import su.terrafirmagreg.modules.device.objects.blocks.BlockLogPile;
import su.terrafirmagreg.modules.device.objects.blocks.BlockMolten;
import su.terrafirmagreg.modules.device.objects.blocks.BlockNestBox;
import su.terrafirmagreg.modules.device.objects.blocks.BlockOven;
import su.terrafirmagreg.modules.device.objects.blocks.BlockOvenChimney;
import su.terrafirmagreg.modules.device.objects.blocks.BlockOvenWall;
import su.terrafirmagreg.modules.device.objects.blocks.BlockPitKiln;
import su.terrafirmagreg.modules.device.objects.blocks.BlockPowderKeg;
import su.terrafirmagreg.modules.device.objects.blocks.BlockQuern;
import su.terrafirmagreg.modules.device.objects.blocks.BlockSmelteryCauldron;
import su.terrafirmagreg.modules.device.objects.blocks.BlockSmelteryFirebox;
import su.terrafirmagreg.modules.device.objects.blocks.BlockSnare;
import su.terrafirmagreg.modules.device.objects.blocks.BlockThatchBed;

public final class BlocksDevice {

  public static BlockAlloyCalculator ALLOY_CALCULATOR;
  public static BlockBearTrap BEAR_TRAP;
  public static BlockSnare SNARE;
  public static BlockCrate CRATE;
  public static BlockBellows BELLOWS;
  public static BlockBlastFurnace BLAST_FURNACE;
  public static BlockBloom BLOOM;
  public static BlockBloomery BLOOMERY;
  public static BlockCharcoalForge CHARCOAL_FORGE;
  public static BlockCharcoalPile CHARCOAL_PILE;
  public static BlockCrucible CRUCIBLE;
  public static BlockFirePit FIRE_PIT;
  public static BlockPitKiln PIT_KILN;
  public static BlockQuern QUERN;
  public static BlockMolten MOLTEN;
  public static BlockLogPile LOG_PILE;
  public static BlockCellarShelf CELLAR_SHELF;
  public static BlockCellarDoor CELLAR_DOOR;
  public static BlockCellarWall CELLAR_WALL;
  public static BlockIceBunker ICE_BUNKER;
  public static BlockInfectedAir INFECTED_AIR;
  public static BlockFreezeDryer FREEZE_DRYER;
  public static BlockNestBox NEST_BOX;
  public static BlockPowderKeg POWDERKEG;
  public static BlockThatchBed THATCH_BED;
  public static BlockGrindstone GRINDSTONE;
  public static BlockElectricForge ELECTRIC_FORGE;
  public static BlockInductionCrucible INDUCTION_CRUCIBLE;
  public static BlockFridge FRIDGE;
  public static BlockLatexExtractor LATEX_EXTRACTOR;
  public static BlockSmelteryCauldron SMELTERY_CAULDRON;
  public static BlockSmelteryFirebox SMELTERY_FIREBOX;
  public static BlockGreenhouseDoor GREENHOUSE_DOOR;
  public static BlockGreenhouseRoof GREENHOUSE_ROOF;
  public static BlockGreenhouseWall GREENHOUSE_WALL;
  public static BlockOven OVEN;
  public static BlockOvenWall OVEN_WALL;
  public static BlockOvenChimney OVEN_CHIMNEY;

  public static void onRegister(RegistryManager registry) {
    //==== Other =================================================================================================//

    ALLOY_CALCULATOR = registry.block(new BlockAlloyCalculator());
    BEAR_TRAP = registry.block(new BlockBearTrap());
    SNARE = registry.block(new BlockSnare());
    CRATE = registry.block(new BlockCrate());
    BELLOWS = registry.block(new BlockBellows());
    BLAST_FURNACE = registry.block(new BlockBlastFurnace());
    BLOOM = registry.block(new BlockBloom());
    BLOOMERY = registry.block(new BlockBloomery());
    CHARCOAL_FORGE = registry.block(new BlockCharcoalForge());
    CHARCOAL_PILE = registry.block(new BlockCharcoalPile());
    CRUCIBLE = registry.block(new BlockCrucible());
    FIRE_PIT = registry.block(new BlockFirePit());
    PIT_KILN = registry.block(new BlockPitKiln());
    QUERN = registry.block(new BlockQuern());
    MOLTEN = registry.block(new BlockMolten());
    LOG_PILE = registry.block(new BlockLogPile());
    CELLAR_SHELF = registry.block(new BlockCellarShelf());
    CELLAR_DOOR = registry.block(new BlockCellarDoor());
    CELLAR_WALL = registry.block(new BlockCellarWall());
    ICE_BUNKER = registry.block(new BlockIceBunker());
    INFECTED_AIR = registry.block(new BlockInfectedAir());
    FREEZE_DRYER = registry.block(new BlockFreezeDryer());
    NEST_BOX = registry.block(new BlockNestBox());
    POWDERKEG = registry.block(new BlockPowderKeg());
    THATCH_BED = registry.block(new BlockThatchBed());
    GRINDSTONE = registry.block(new BlockGrindstone());
    ELECTRIC_FORGE = registry.block(new BlockElectricForge());
    INDUCTION_CRUCIBLE = registry.block(new BlockInductionCrucible());
    FRIDGE = registry.block(new BlockFridge());
    LATEX_EXTRACTOR = registry.block(new BlockLatexExtractor());
    SMELTERY_CAULDRON = registry.block(new BlockSmelteryCauldron());
    SMELTERY_FIREBOX = registry.block(new BlockSmelteryFirebox());
    GREENHOUSE_DOOR = registry.block(new BlockGreenhouseDoor());
    GREENHOUSE_ROOF = registry.block(new BlockGreenhouseRoof());
    GREENHOUSE_WALL = registry.block(new BlockGreenhouseWall());
    OVEN = registry.block(new BlockOven());
    OVEN_WALL = registry.block(new BlockOvenWall());
    OVEN_CHIMNEY = registry.block(new BlockOvenChimney());
  }

}
