package su.terrafirmagreg.modules.animal.feature.mapping;

import su.terrafirmagreg.api.util.DataFixUtils;
import su.terrafirmagreg.framework.manager.feature.spi.FeatureBase;
import su.terrafirmagreg.modules.animal.init.BlocksAnimal;
import su.terrafirmagreg.modules.animal.init.EntitiesAnimal;
import su.terrafirmagreg.modules.animal.init.ItemsAnimal;
import su.terrafirmagreg.modules.animal.init.SoundsAnimal;

public class FeatureRemappingAnimal extends FeatureBase {

  static {
    DataFixUtils.put(DataFixUtils.BLOCK_MAP, m -> {
      m.put("nest_box", BlocksAnimal.NEST_BOX);
    });

    DataFixUtils.put(DataFixUtils.ITEM_MAP, m -> {
      m.put("bladder", ItemsAnimal.BLADDER);
      m.put("halter", ItemsAnimal.HALTER);
      m.put("product/silk_cloth", ItemsAnimal.SILK_CLOTH);
      m.put("product/wool_cloth", ItemsAnimal.WOOL_CLOTH);
      m.put("product/wool_yarn", ItemsAnimal.WOOL_YARN);
      m.put("product/wool", ItemsAnimal.WOOL);
    });

    DataFixUtils.put(DataFixUtils.ENTITY_MAP, m -> {
      m.put("sheeptfc", EntitiesAnimal.SHEEP);
      m.put("cowtfc", EntitiesAnimal.COW);
      m.put("grizzlybeartfc", EntitiesAnimal.GRIZZLYBEAR);
      m.put("chickentfc", EntitiesAnimal.CHICKEN);
      m.put("pheasanttfc", EntitiesAnimal.PHEASANT);
      m.put("deertfc", EntitiesAnimal.DEER);
      m.put("pigtfc", EntitiesAnimal.PIG);
      m.put("wolftfc", EntitiesAnimal.WOLF);
      m.put("rabbittfc", EntitiesAnimal.RABBIT);
      m.put("horsetfc", EntitiesAnimal.HORSE);
      m.put("donkeytfc", EntitiesAnimal.DONKEY);
      m.put("muletfc", EntitiesAnimal.MULE);
      m.put("polarbeartfc", EntitiesAnimal.POLARBEAR);
      m.put("parrottfc", EntitiesAnimal.PARROT);
      m.put("llamatfc", EntitiesAnimal.LLAMA);
      m.put("ocelottfc", EntitiesAnimal.OCELOT);
      m.put("panthertfc", EntitiesAnimal.PANTHER);
      m.put("ducktfc", EntitiesAnimal.DUCK);
      m.put("alpacatfc", EntitiesAnimal.ALPACA);
      m.put("goattfc", EntitiesAnimal.GOAT);
      m.put("sabertoothtfc", EntitiesAnimal.SABERTOOTH);
      m.put("cameltfc", EntitiesAnimal.CAMEL);
      m.put("liontfc", EntitiesAnimal.LION);
      m.put("hyenatfc", EntitiesAnimal.HYENA);
      m.put("direwolftfc", EntitiesAnimal.DIREWOLF);
      m.put("haretfc", EntitiesAnimal.HARE);
      m.put("boartfc", EntitiesAnimal.BOAR);
      m.put("zebutfc", EntitiesAnimal.ZEBU);
      m.put("gazelletfc", EntitiesAnimal.GAZELLE);
      m.put("wildebeesttfc", EntitiesAnimal.WILDEBEEST);
      m.put("quailtfc", EntitiesAnimal.QUAIL);
      m.put("grousetfc", EntitiesAnimal.GROUSE);
      m.put("mongoosetfc", EntitiesAnimal.MONGOOSE);
      m.put("turkeytfc", EntitiesAnimal.TURKEY);
      m.put("jackaltfc", EntitiesAnimal.JACKAL);
      m.put("muskoxtfc", EntitiesAnimal.MUSKOX);
      m.put("yaktfc", EntitiesAnimal.YAK);
      m.put("blackbeartfc", EntitiesAnimal.BLACKBEAR);
      m.put("cougartfc", EntitiesAnimal.COUGAR);
      m.put("coyotetfc", EntitiesAnimal.COYOTE);
    });

    DataFixUtils.put(DataFixUtils.SOUND_MAP, m -> {
      m.put("animal.alpaca.cry", SoundsAnimal.ANIMAL_ALPACA_CRY);
      m.put("animal.alpaca.death", SoundsAnimal.ANIMAL_ALPACA_DEATH);
      m.put("animal.alpaca.hurt", SoundsAnimal.ANIMAL_ALPACA_HURT);
      m.put("animal.alpaca.say", SoundsAnimal.ANIMAL_ALPACA_SAY);
      m.put("animal.bear.cry", SoundsAnimal.ANIMAL_BEAR_CRY);
      m.put("animal.bear.death", SoundsAnimal.ANIMAL_BEAR_DEATH);
      m.put("animal.bear.hurt", SoundsAnimal.ANIMAL_BEAR_HURT);
      m.put("animal.bear.say", SoundsAnimal.ANIMAL_BEAR_SAY);
      m.put("animal.boar.death", SoundsAnimal.ANIMAL_BOAR_DEATH);
      m.put("animal.boar.hurt", SoundsAnimal.ANIMAL_BOAR_HURT);
      m.put("animal.boar.say", SoundsAnimal.ANIMAL_BOAR_SAY);
      m.put("animal.camel.cry", SoundsAnimal.ANIMAL_CAMEL_CRY);
      m.put("animal.camel.death", SoundsAnimal.ANIMAL_CAMEL_DEATH);
      m.put("animal.camel.hurt", SoundsAnimal.ANIMAL_CAMEL_HURT);
      m.put("animal.camel.say", SoundsAnimal.ANIMAL_CAMEL_SAY);
      m.put("animal.cougar.cry", SoundsAnimal.ANIMAL_COUGAR_CRY);
      m.put("animal.cougar.death", SoundsAnimal.ANIMAL_COUGAR_DEATH);
      m.put("animal.cougar.hurt", SoundsAnimal.ANIMAL_COUGAR_HURT);
      m.put("animal.cougar.say", SoundsAnimal.ANIMAL_COUGAR_SAY);
      m.put("animal.coyote.cry", SoundsAnimal.ANIMAL_COYOTE_CRY);
      m.put("animal.coyote.death", SoundsAnimal.ANIMAL_COYOTE_DEATH);
      m.put("animal.coyote.hurt", SoundsAnimal.ANIMAL_COYOTE_HURT);
      m.put("animal.coyote.say", SoundsAnimal.ANIMAL_COYOTE_SAY);
      m.put("animal.deer.cry", SoundsAnimal.ANIMAL_DEER_CRY);
      m.put("animal.deer.death", SoundsAnimal.ANIMAL_DEER_DEATH);
      m.put("animal.deer.hurt", SoundsAnimal.ANIMAL_DEER_HURT);
      m.put("animal.deer.say", SoundsAnimal.ANIMAL_DEER_SAY);
      m.put("animal.direwolf.cry", SoundsAnimal.ANIMAL_DIREWOLF_CRY);
      m.put("animal.direwolf.death", SoundsAnimal.ANIMAL_DIREWOLF_DEATH);
      m.put("animal.direwolf.hurt", SoundsAnimal.ANIMAL_DIREWOLF_HURT);
      m.put("animal.direwolf.say", SoundsAnimal.ANIMAL_DIREWOLF_SAY);
      m.put("animal.duck.cry", SoundsAnimal.ANIMAL_DUCK_CRY);
      m.put("animal.duck.death", SoundsAnimal.ANIMAL_DUCK_DEATH);
      m.put("animal.duck.hurt", SoundsAnimal.ANIMAL_DUCK_HURT);
      m.put("animal.duck.say", SoundsAnimal.ANIMAL_DUCK_SAY);
      m.put("animal.feline.step", SoundsAnimal.ANIMAL_FELINE_STEP);
      m.put("animal.gazelle.death", SoundsAnimal.ANIMAL_GAZELLE_DEATH);
      m.put("animal.gazelle.hurt", SoundsAnimal.ANIMAL_GAZELLE_HURT);
      m.put("animal.gazelle.say", SoundsAnimal.ANIMAL_GAZELLE_SAY);
      m.put("animal.goat.cry", SoundsAnimal.ANIMAL_GOAT_CRY);
      m.put("animal.goat.death", SoundsAnimal.ANIMAL_GOAT_DEATH);
      m.put("animal.goat.hurt", SoundsAnimal.ANIMAL_GOAT_HURT);
      m.put("animal.goat.say", SoundsAnimal.ANIMAL_GOAT_SAY);
      m.put("animal.grouse.death", SoundsAnimal.ANIMAL_GROUSE_DEATH);
      m.put("animal.grouse.hurt", SoundsAnimal.ANIMAL_GROUSE_HURT);
      m.put("animal.grouse.say", SoundsAnimal.ANIMAL_GROUSE_SAY);
      m.put("animal.hyena.cry", SoundsAnimal.ANIMAL_HYENA_CRY);
      m.put("animal.hyena.death", SoundsAnimal.ANIMAL_HYENA_DEATH);
      m.put("animal.hyena.hurt", SoundsAnimal.ANIMAL_HYENA_HURT);
      m.put("animal.hyena.say", SoundsAnimal.ANIMAL_HYENA_SAY);
      m.put("animal.zebu.death", SoundsAnimal.ANIMAL_ZEBU_DEATH);
      m.put("animal.zebu.hurt", SoundsAnimal.ANIMAL_ZEBU_HURT);
      m.put("animal.zebu.say", SoundsAnimal.ANIMAL_ZEBU_SAY);
      m.put("animal.jackal.cry", SoundsAnimal.ANIMAL_JACKAL_CRY);
      m.put("animal.jackal.death", SoundsAnimal.ANIMAL_JACKAL_DEATH);
      m.put("animal.jackal.hurt", SoundsAnimal.ANIMAL_JACKAL_HURT);
      m.put("animal.jackal.say", SoundsAnimal.ANIMAL_JACKAL_SAY);
      m.put("animal.lion.cry", SoundsAnimal.ANIMAL_LION_CRY);
      m.put("animal.lion.death", SoundsAnimal.ANIMAL_LION_DEATH);
      m.put("animal.lion.hurt", SoundsAnimal.ANIMAL_LION_HURT);
      m.put("animal.lion.say", SoundsAnimal.ANIMAL_LION_SAY);
      m.put("animal.mongoose.death", SoundsAnimal.ANIMAL_MONGOOSE_DEATH);
      m.put("animal.mongoose.hurt", SoundsAnimal.ANIMAL_MONGOOSE_HURT);
      m.put("animal.mongoose.say", SoundsAnimal.ANIMAL_MONGOOSE_SAY);
      m.put("animal.muskox.death", SoundsAnimal.ANIMAL_MUSKOX_DEATH);
      m.put("animal.muskox.hurt", SoundsAnimal.ANIMAL_MUSKOX_HURT);
      m.put("animal.muskox.say", SoundsAnimal.ANIMAL_MUSKOX_SAY);
      m.put("animal.panther.cry", SoundsAnimal.ANIMAL_PANTHER_CRY);
      m.put("animal.panther.death", SoundsAnimal.ANIMAL_PANTHER_DEATH);
      m.put("animal.panther.hurt", SoundsAnimal.ANIMAL_PANTHER_HURT);
      m.put("animal.panther.say", SoundsAnimal.ANIMAL_PANTHER_SAY);
      m.put("animal.pheasant.death", SoundsAnimal.ANIMAL_PHEASANT_DEATH);
      m.put("animal.pheasant.hurt", SoundsAnimal.ANIMAL_PHEASANT_HURT);
      m.put("animal.pheasant.say", SoundsAnimal.ANIMAL_PHEASANT_SAY);
      m.put("animal.quail.death", SoundsAnimal.ANIMAL_QUAIL_DEATH);
      m.put("animal.quail.hurt", SoundsAnimal.ANIMAL_QUAIL_HURT);
      m.put("animal.quail.say", SoundsAnimal.ANIMAL_QUAIL_SAY);
      m.put("animal.rooster.cry", SoundsAnimal.ANIMAL_ROOSTER_CRY);
      m.put("animal.sabertooth.cry", SoundsAnimal.ANIMAL_SABERTOOTH_CRY);
      m.put("animal.sabertooth.death", SoundsAnimal.ANIMAL_SABERTOOTH_DEATH);
      m.put("animal.sabertooth.hurt", SoundsAnimal.ANIMAL_SABERTOOTH_HURT);
      m.put("animal.sabertooth.say", SoundsAnimal.ANIMAL_SABERTOOTH_SAY);
      m.put("animal.turkey.death", SoundsAnimal.ANIMAL_TURKEY_DEATH);
      m.put("animal.turkey.hurt", SoundsAnimal.ANIMAL_TURKEY_HURT);
      m.put("animal.turkey.say", SoundsAnimal.ANIMAL_TURKEY_SAY);
      m.put("animal.wildebeest.death", SoundsAnimal.ANIMAL_WILDEBEEST_DEATH);
      m.put("animal.wildebeest.hurt", SoundsAnimal.ANIMAL_WILDEBEEST_HURT);
      m.put("animal.wildebeest.say", SoundsAnimal.ANIMAL_WILDEBEEST_SAY);
      m.put("animal.yak.say", SoundsAnimal.ANIMAL_YAK_SAY);
      m.put("animal.yak.death", SoundsAnimal.ANIMAL_YAK_DEATH);
      m.put("animal.yak.hurt", SoundsAnimal.ANIMAL_YAK_HURT);
    });
  }
}
