package su.terrafirmagreg.modules.animal.init;

import su.terrafirmagreg.api.util.ModelUtils;
import su.terrafirmagreg.framework.registry.api.IRegistryManager;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalAbstractHorse;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalAlpaca;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalBlackBear;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalBoar;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalCamel;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalChicken;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalCougar;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalCow;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalCoyote;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalDeer;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalDireWolf;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalDuck;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalGazelle;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalGoat;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalGrizzlyBear;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalGrouse;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalHare;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalHorse;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalHyena;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalJackal;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalLion;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalLlama;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalMongoose;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalMuskOx;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalOcelot;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalPanther;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalParrot;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalPheasant;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalPig;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalPolarBear;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalQuail;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalRabbit;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalSaberTooth;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalSheep;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalTurkey;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalWildebeest;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalWolf;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalYak;
import su.terrafirmagreg.modules.animal.client.render.RenderAnimalZebu;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalBoar;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalDeer;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalGazelle;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalHare;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalMongoose;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalPheasant;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalRabbit;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalTurkey;
import su.terrafirmagreg.modules.animal.object.entity.huntable.EntityAnimalWildebeest;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalAlpaca;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalCamel;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalChicken;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalCow;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalDonkey;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalDuck;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalGoat;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalGrouse;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalHorse;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalLlama;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalMule;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalMuskOx;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalOcelot;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalParrot;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalPig;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalQuail;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalSheep;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalWolf;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalYak;
import su.terrafirmagreg.modules.animal.object.entity.livestock.EntityAnimalZebu;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalBlackBear;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalCougar;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalCoyote;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalDireWolf;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalGrizzlyBear;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalHyena;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalJackal;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalLion;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalPanther;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalPolarBear;
import su.terrafirmagreg.modules.animal.object.entity.predator.EntityAnimalSaberTooth;

import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

import java.util.function.Supplier;

public final class EntitiesAnimal {

  public static Supplier<EntityEntry> SHEEP;
  public static Supplier<EntityEntry> COW;
  public static Supplier<EntityEntry> GRIZZLYBEAR;
  public static Supplier<EntityEntry> CHICKEN;
  public static Supplier<EntityEntry> PHEASANT;
  public static Supplier<EntityEntry> DEER;
  public static Supplier<EntityEntry> PIG;
  public static Supplier<EntityEntry> WOLF;
  public static Supplier<EntityEntry> RABBIT;
  public static Supplier<EntityEntry> HORSE;
  public static Supplier<EntityEntry> DONKEY;
  public static Supplier<EntityEntry> MULE;
  public static Supplier<EntityEntry> POLARBEAR;
  public static Supplier<EntityEntry> PARROT;
  public static Supplier<EntityEntry> LLAMA;
  public static Supplier<EntityEntry> OCELOT;
  public static Supplier<EntityEntry> PANTHER;
  public static Supplier<EntityEntry> DUCK;
  public static Supplier<EntityEntry> ALPACA;
  public static Supplier<EntityEntry> GOAT;
  public static Supplier<EntityEntry> SABERTOOTH;
  public static Supplier<EntityEntry> CAMEL;
  public static Supplier<EntityEntry> LION;
  public static Supplier<EntityEntry> HYENA;
  public static Supplier<EntityEntry> DIREWOLF;
  public static Supplier<EntityEntry> HARE;
  public static Supplier<EntityEntry> BOAR;
  public static Supplier<EntityEntry> ZEBU;
  public static Supplier<EntityEntry> GAZELLE;
  public static Supplier<EntityEntry> WILDEBEEST;
  public static Supplier<EntityEntry> QUAIL;
  public static Supplier<EntityEntry> GROUSE;
  public static Supplier<EntityEntry> MONGOOSE;
  public static Supplier<EntityEntry> TURKEY;
  public static Supplier<EntityEntry> JACKAL;
  public static Supplier<EntityEntry> MUSKOX;
  public static Supplier<EntityEntry> YAK;
  public static Supplier<EntityEntry> BLACKBEAR;
  public static Supplier<EntityEntry> COUGAR;
  public static Supplier<EntityEntry> COYOTE;

  public static void onRegister(IRegistryManager registry) {

    SHEEP = registry.entity("sheep", EntityAnimalSheep.class, 0xFFFFFF, 0xFF6347);
    COW = registry.entity("cow", EntityAnimalCow.class, 0xA52A2A, 0xFFFFFF);
    GRIZZLYBEAR = registry.entity("grizzlybear", EntityAnimalGrizzlyBear.class, 0xB22222, 0xDEB887);
    CHICKEN = registry.entity("chicken", EntityAnimalChicken.class, 0x557755, 0xFFF91F);
    PHEASANT = registry.entity("pheasant", EntityAnimalPheasant.class, 0x5577FF, 0xFFFA90);
    DEER = registry.entity("deer", EntityAnimalDeer.class, 0x55FF55, 0x5FFAAF);
    PIG = registry.entity("pig", EntityAnimalPig.class, 0xAA7722, 0xFFEBCD);
    WOLF = registry.entity("wolf", EntityAnimalWolf.class, 0xB0ACAC, 0x796555);
    RABBIT = registry.entity("rabbit", EntityAnimalRabbit.class, 0x885040, 0x462612);
    HORSE = registry.entity("horse", EntityAnimalHorse.class, 0xA5886B, 0xABA400);
    DONKEY = registry.entity("donkey", EntityAnimalDonkey.class, 0x493C32, 0x756659);
    MULE = registry.entity("mule", EntityAnimalMule.class, 0x180200, 0x482D1A);
    POLARBEAR = registry.entity("polarbear", EntityAnimalPolarBear.class, 0xF1FFF1, 0xA0A0A0);
    PARROT = registry.entity("parrot", EntityAnimalParrot.class, 0x885040, 0xB0ACAC);
    LLAMA = registry.entity("llama", EntityAnimalLlama.class, 0xA52A2A, 0xAA7722);
    OCELOT = registry.entity("ocelot", EntityAnimalOcelot.class, 0x3527FA, 0x7F23A0);
    PANTHER = registry.entity("panther", EntityAnimalPanther.class, 0x000066, 0x000000);
    DUCK = registry.entity("duck", EntityAnimalDuck.class, 0xFFF91F, 0x462612);
    ALPACA = registry.entity("alpaca", EntityAnimalAlpaca.class, 0x00CC66, 0x006633);
    GOAT = registry.entity("goat", EntityAnimalGoat.class, 0xA0A0A0, 0x404040);
    SABERTOOTH = registry.entity("sabertooth", EntityAnimalSaberTooth.class, 0xFF8000, 0xFFD700);
    CAMEL = registry.entity("camel", EntityAnimalCamel.class, 0xA5886B, 0x006633);
    LION = registry.entity("lion", EntityAnimalLion.class, 0xDAA520, 0xA0522D);
    HYENA = registry.entity("hyena", EntityAnimalHyena.class, 0x666600, 0x331900);
    DIREWOLF = registry.entity("direwolf", EntityAnimalDireWolf.class, 0x343434, 0x978f7e);
    HARE = registry.entity("hare", EntityAnimalHare.class, 0x866724, 0xDADADA);
    BOAR = registry.entity("boar", EntityAnimalBoar.class, 0x463c09, 0xe39ad8);
    ZEBU = registry.entity("zebu", EntityAnimalZebu.class, 0x2c2507, 0xbcb38e);
    GAZELLE = registry.entity("gazelle", EntityAnimalGazelle.class, 0xa9a76f, 0xc0ab55);
    WILDEBEEST = registry.entity("wildebeest", EntityAnimalWildebeest.class, 0x696142, 0x9c8115);
    QUAIL = registry.entity("quail", EntityAnimalQuail.class, 0x237ddc, 0xe3e36d);
    GROUSE = registry.entity("grouse", EntityAnimalGrouse.class, 0xf7a100, 0x71ffd0);
    MONGOOSE = registry.entity("mongoose", EntityAnimalMongoose.class, 0xf9f50f, 0x90ec7f);
    TURKEY = registry.entity("turkey", EntityAnimalTurkey.class, 0xad1d1d, 0xeaa659);
    JACKAL = registry.entity("jackal", EntityAnimalJackal.class, 0xb8762b, 0xffffff);
    MUSKOX = registry.entity("muskox", EntityAnimalMuskOx.class, 0x620d55, 0xcdaf4f);
    YAK = registry.entity("yak", EntityAnimalYak.class, 0x837669, 0x3e3d7c);
    BLACKBEAR = registry.entity("blackbear", EntityAnimalBlackBear.class, 0x000000, 0xa18f6c);
    COUGAR = registry.entity("cougar", EntityAnimalCougar.class, 0x817a00, 0xdcd889);
    COYOTE = registry.entity("coyote", EntityAnimalCoyote.class, 0xb7bc88, 0xdac213);
  }

  @SideOnly(Side.CLIENT)
  public static void onClientRegister(IRegistryManager registry) {

    ModelUtils.entity(EntityAnimalSheep.class, RenderAnimalSheep::new);
    ModelUtils.entity(EntityAnimalCow.class, RenderAnimalCow::new);
    ModelUtils.entity(EntityAnimalGrizzlyBear.class, RenderAnimalGrizzlyBear::new);
    ModelUtils.entity(EntityAnimalChicken.class, RenderAnimalChicken::new);
    ModelUtils.entity(EntityAnimalPheasant.class, RenderAnimalPheasant::new);
    ModelUtils.entity(EntityAnimalDeer.class, RenderAnimalDeer::new);
    ModelUtils.entity(EntityAnimalPig.class, RenderAnimalPig::new);
    ModelUtils.entity(EntityAnimalWolf.class, RenderAnimalWolf::new);
    ModelUtils.entity(EntityAnimalRabbit.class, RenderAnimalRabbit::new);
    ModelUtils.entity(EntityAnimalHorse.class, RenderAnimalHorse::new);
    ModelUtils.entity(EntityAnimalDonkey.class, RenderAnimalAbstractHorse::new);
    ModelUtils.entity(EntityAnimalMule.class, RenderAnimalAbstractHorse::new);
    ModelUtils.entity(EntityAnimalPolarBear.class, RenderAnimalPolarBear::new);
    ModelUtils.entity(EntityAnimalParrot.class, RenderAnimalParrot::new);
    ModelUtils.entity(EntityAnimalLlama.class, RenderAnimalLlama::new);
    ModelUtils.entity(EntityAnimalOcelot.class, RenderAnimalOcelot::new);
    ModelUtils.entity(EntityAnimalPanther.class, RenderAnimalPanther::new);
    ModelUtils.entity(EntityAnimalDuck.class, RenderAnimalDuck::new);
    ModelUtils.entity(EntityAnimalAlpaca.class, RenderAnimalAlpaca::new);
    ModelUtils.entity(EntityAnimalGoat.class, RenderAnimalGoat::new);
    ModelUtils.entity(EntityAnimalSaberTooth.class, RenderAnimalSaberTooth::new);
    ModelUtils.entity(EntityAnimalCamel.class, RenderAnimalCamel::new);
    ModelUtils.entity(EntityAnimalLion.class, RenderAnimalLion::new);
    ModelUtils.entity(EntityAnimalHyena.class, RenderAnimalHyena::new);
    ModelUtils.entity(EntityAnimalDireWolf.class, RenderAnimalDireWolf::new);
    ModelUtils.entity(EntityAnimalHare.class, RenderAnimalHare::new);
    ModelUtils.entity(EntityAnimalBoar.class, RenderAnimalBoar::new);
    ModelUtils.entity(EntityAnimalZebu.class, RenderAnimalZebu::new);
    ModelUtils.entity(EntityAnimalGazelle.class, RenderAnimalGazelle::new);
    ModelUtils.entity(EntityAnimalWildebeest.class, RenderAnimalWildebeest::new);
    ModelUtils.entity(EntityAnimalQuail.class, RenderAnimalQuail::new);
    ModelUtils.entity(EntityAnimalGrouse.class, RenderAnimalGrouse::new);
    ModelUtils.entity(EntityAnimalMongoose.class, RenderAnimalMongoose::new);
    ModelUtils.entity(EntityAnimalTurkey.class, RenderAnimalTurkey::new);
    ModelUtils.entity(EntityAnimalJackal.class, RenderAnimalJackal::new);
    ModelUtils.entity(EntityAnimalMuskOx.class, RenderAnimalMuskOx::new);
    ModelUtils.entity(EntityAnimalYak.class, RenderAnimalYak::new);
    ModelUtils.entity(EntityAnimalBlackBear.class, RenderAnimalBlackBear::new);
    ModelUtils.entity(EntityAnimalCougar.class, RenderAnimalCougar::new);
    ModelUtils.entity(EntityAnimalCoyote.class, RenderAnimalCoyote::new);
  }
}
