name: Deploy
run-name: "Deploy #${{ github.run_number }} by @${{ github.actor }}"

env:
  RELEASE_TYPE: "release"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  info:
    name: Project Info
    runs-on: ubuntu-latest
    outputs:
      mod_version: ${{ steps.mod_version.outputs.value }}
      mod_name: ${{ steps.mod_name.outputs.value }}
      minecraft_version: ${{ steps.minecraft_version.outputs.value }}
      exists: ${{ steps.check_tag.outputs.exists }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Get mod name
        id: mod_name
        uses: dschanoeh/get-property@v1.2.0
        with:
          file: gradle.properties
          property: mod_name

      - name: Get mod version
        id: mod_version
        uses: dschanoeh/get-property@v1.2.0
        with:
          file: gradle.properties
          property: mod_version

      - name: Get minecraft version
        id: minecraft_version
        uses: dschanoeh/get-property@v1.2.0
        with:
          file: gradle.properties
          property: minecraft_version

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check_tag
        with:
          tag: ${{ steps.mod_version.outputs.value }}


  build:
    name: Project Build
    needs: [info]
    runs-on: ubuntu-latest
    if: needs.info.outputs.exists != 'true'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: SetUp JDK
        uses: actions/setup-java@v4.6.0
        with:
          java-version: |
            8
            17
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.5.0
        with:
          cache-write-only: false
          generate-job-summary: false
          gradle-home-cache-includes: |
            caches
            notifications
            jdks
            wrapper

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3.5.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: build

      - name: Upload jar
        id: upload_file
        uses: actions/upload-artifact@v4.6.0
        with:
          path: build/libs/${{ needs.info.outputs.mod_name }}-${{ needs.info.outputs.mod_version }}.jar

      - name: Release
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-dependencies: |
            gregtech-ce-unofficial(required)
            terrafirmacraft(include)

          curseforge-id: ${{ vars.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-dependencies: |
            gregtech-ce-unofficial(required)
            terrafirmacraft(include)

          github-tag: ${{ needs.info.outputs.mod_version }}
          github-generate-changelog: true
          github-draft: false
          github-prerelease: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: build/libs/${{ needs.info.outputs.mod_name }}-${{ needs.info.outputs.mod_version }}.jar

          name: "${{ needs.info.outputs.mod_name }}-${{ needs.info.outputs.mod_version }}"
          version: ${{ needs.info.outputs.mod_version }}
          version-type: ${{ env.RELEASE_TYPE }}

          loaders: forge
          game-versions: ${{ needs.info.outputs.minecraft_version }}
          game-version-filter: none
          java: 8
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
